Allow numbers in pageRanges
w3c/webdriver-bidi pull request #372
Opened 2023-02-24 13:04 UTC by lutien

To make it easier for the clients and align with [Webdriver spec ](https://www.w3.org/TR/webdriver/#print) we should allow `pageRanges` accept not just strings but numbers as well.

2023-02-24 13:25 UTC, jgraham requested changes

2023-02-24 13:25 UTC, jgraham commented on index.bs
> +        ?pageRanges: [*(number / text)],
Should be `js-uint` rather than `number`.

2023-02-24 13:34 UTC, jgraham approved these changes

2023-02-27 10:11 UTC, lutien commented
@jgraham, could you merge it for me?
I don't have rights to merge here.

2023-02-27 10:13 UTC, jgraham commented
Usually I'd wait for someone from another vendor to approve the change. But I think since this is just brining the spec in line with what was in WebDriver classic, it's OK to treat it as a bugfix and merge (but if someone disagrees with this, please let me know and we can discuss the change!).

2023-02-27 10:14 UTC, merged