Use `.and` instead of composition
w3c/webdriver-bidi pull request #461
Opened 2023-07-03 13:52 UTC by jrandolf

CDDL doesn't allow composition of maps.

2023-07-03 14:26 UTC, thiagowfx approved these changes

2023-07-04 09:27 UTC, jgraham requested changes
I don't think this is right? 

```

   A ".and" control on a type indicates that the data item matches both
   the left-hand-side type and the type given as the right-hand side.
   (Formally, the resulting type is the intersection of the two types
   given.)
```

We don't want an intersection, but a union.

2023-07-04 09:35 UTC, jrandolf commented
I'm pretty sure we want an intersection type. We want `script.RegExpRemoteValue` to contain the keys for `script.RegExpLocalValue` and the keys presented in the map.

2023-07-04 13:01 UTC, jgraham approved these changes
OK, based on discussions, it seems like I didn't understand what CDDL intended here.

2023-07-04 13:01 UTC, merged