(cddl): remove brackets from range
w3c/webdriver-bidi pull request #599
Opened 2023-11-09 18:50 UTC by christian-bromann

I can't really read of the CDDL spec whether or not extra brackets around type primitives, e.g. ranges, can be ignored or not but if we assume not, an opening bracket (especially as part of a key assignment) creates a group that has to consist of a key value pair and can't be a single type.

2023-11-09 21:45 UTC, thiagowfx approved these changes

2023-11-10 09:20 UTC, OrKoN commented
I recall there was some ambiguity without the brackets. @jrandolf PTAL

2023-11-10 10:48 UTC, thiagowfx requested changes
Undo approval

2023-11-10 16:45 UTC, christian-bromann commented
This is why I mentioned that the spec is not very clear about this. One could argue that the `0.1..2.0` part within `0.1..2.0 .default 1.0` can be seen as a single type (a range) and resolves into `[range] .default [float]`. That said, I've seen the following example while skimming through the CDDL spec:

```
label = bstr .size (1..63)
```

which proves your assumption to be correct. Therefor I will go ahead and close this.

Just fyi: I am working on a [cddl parser](https://github.com/christian-bromann/cddl) where these nit picky details make a big difference. Thanks for your feedback!

2023-11-10 16:45 UTC, closed without merging

2023-11-13 04:58 UTC, jrandolf commented
@christian-bromann You may want to check out https://github.com/anweiss/cddl. It's already fully compliant and we use it as our backend for code generation (https://github.com/google/cddlconv).