Add a capability for returning the default user agent header value
w3c/webdriver-bidi pull request #652
Opened 2024-02-07 08:25 UTC by OrKoN

Closes #446

2024-02-07 08:38 UTC, jrandolf requested changes
The CDDL also needs to be updated.

2024-02-07 08:43 UTC, jrandolf approved these changes

2024-02-08 10:33 UTC, whimboo requested changes
We discussed this yesterday and actually wonder if it wouldn't even be better to add the `userAgent` capability to the WebDriver classic specification. That way we wouldn't have to make this capability BiDi specific.

If you agree this PR would have to be changed to only update the CDDL definition.

2024-02-08 12:05 UTC, OrKoN commented
@whimboo is there a requirement for that from the classic users?

2024-02-08 12:12 UTC, jgraham commented
So, in detail, the proposal as specified here is that you'd get an additional capability if the implementation _supports_ BiDi irrespective of whether BiDi is requested or enabled (I think that's different to what I said in the previous discussion).

I still think that doesn't make any sense, and we should just add the capability directly to classic.

2024-03-07 14:41 UTC, whimboo approved these changes
Looks good to me. Thanks.

2024-03-07 14:42 UTC, merged